version: '3.9'
networks:
  collab-net:
services:
  redis:
    container_name: collab-redis
    hostname: collab-redis
    image: "redis:alpine"
    logging:
      driver: "none"
    ports:
      - 6379:6379
    networks:
      - collab-net
  database:
    container_name: collab-ts
    hostname: collab-ts
    image: "timescale/timescaledb-ha:pg15-latest"
    logging:
      driver: "none"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collab_ts
    ports:
      - 5432:5432
    networks:
      - collab-net
